version: '3.6'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  keepalived:
    image: 'colovu/keepalived:latest'
    privileged: true
    volumes:
      - '/tmp/conf:/srv/conf'
    environment:
      - KEEPALIVED_VIPS=192.168.200.1,172.20.0.100
      - ENV_DEBUG=yes
